using Microsoft.Agents.AI;
using Microsoft.Extensions.AI;
using ModelContextProtocol.Client;
using Ollama;
using OllamaSharp;
using OllamaSharp.Models.Chat;

Console.WriteLine("--- Initializing Remote Mentorship Swarm ---");

// 2. Initialize the Agent
OllamaApiClient ollamaApiClient = new OllamaApiClient(OllamaConfiguration.Endpoint, OllamaConfiguration.Model)
    .WithLongTimeout();

using var client = new ChatClientBuilder(ollamaApiClient)
    .UseFunctionInvocation()
    .Build();

using var httpClient = new HttpClient();

var mcpClient = await McpClient.CreateAsync(
    new HttpClientTransport(new HttpClientTransportOptions() 
    { 
        Endpoint = new Uri("https://learn.microsoft.com/api/mcp"),
        TransportMode = HttpTransportMode.StreamableHttp
    }, httpClient, ownsHttpClient: true)
    );

var mcpTools = (await mcpClient.ListToolsAsync().ConfigureAwait(false)).Cast<AIFunction>();
var approvalRequiredTools = mcpTools.Select(tool => new ApprovalRequiredAIFunction(tool)).ToList();

AIAgent mentorAgent = ollamaApiClient
    .AsAIAgent(
        name: "ArchitectureMentor",
        instructions: "You answer technical .NET questions. You MUST use the 'microsoft_docs_search' tool from the 'microsoft_learn' server before answering."+
        "If the approval for a tool call is required, and user denies it, you must not proceed with the tool call and inform the user accordingly and DO NOT provide alternative solutions/information.",
        //instructions: "You are a Senior Architecture Mentor. To provide accurate answers, always start by calling the 'microsoft_docs_search' tool.",
        tools: [.. approvalRequiredTools]
    );

// 3. Begin the Stateful Session
AgentSession session = await mentorAgent.CreateSessionAsync();
//string prompt = "What are the exact C# classes required to implement the Agent-to-Agent (A2A) protocol in the Microsoft Agent Framework?";
string prompt = "What are the exact C# classes required to implement the Agent-to-Agent (A2A) protocol using the Microsoft.Agents.AI namespace?";

Console.WriteLine($"\nJunior Dev: {prompt}\n");

// 4. Initial Execution (The agent realizes it needs to search and pauses)
AgentResponse response = await mentorAgent.RunAsync(prompt, session);

// Extract any pending approval requests generated by the agent
List<ToolApprovalRequestContent> approvalRequests = response.Messages
    .SelectMany(m => m.Contents)
    .OfType<ToolApprovalRequestContent>()
    .ToList();

// 5. The Governance Loop (Human-in-the-Loop)
while (approvalRequests.Count > 0)
{
    // Process one request at a time, then refresh pending approvals from latest response.
    var request = approvalRequests[0];

    // Present the agent's intent to the human manager
    Console.WriteLine("\n[SECURITY AUDIT] The agent is attempting to execute a remote tool.");
    if (request.ToolCall is ToolCallContent toolCallContent)
    {
        Message.ToolCall toolCall = (Message.ToolCall)toolCallContent.RawRepresentation!;
        Console.WriteLine($"Target Tool:   {(toolCall).Function?.Name}");

        string toolArgs = string.Join(", ", toolCall.Function?.Arguments?.Select(x => $"{x.Key}: '{x.Value}'") ?? []);
        Console.WriteLine($"Arguments:     {toolArgs}");
    }
    else
    {
        Console.WriteLine("Target Tool:   [Unknown MCP tool call payload]");
    }

    Console.Write("\nApprove network request? (Y/N): ");
    ConsoleKey key;
    do
    {
        key = Console.ReadKey(intercept: true).Key;
    } while (key is not ConsoleKey.Y and not ConsoleKey.N);
    Console.WriteLine(key == ConsoleKey.Y ? "Y" : "N");

    bool isApproved = key == ConsoleKey.Y;

    // Package the human's decision back into a ChatMessage
    var approvalMessage = new ChatMessage(Microsoft.Extensions.AI.ChatRole.User, [request.CreateResponse(isApproved)]);

    // Push the human's approval (or denial) back to the agent and resume execution
    Console.WriteLine("\n[System] Resuming agent execution...");
    response = await mentorAgent.RunAsync(approvalMessage, session);

    // Check if the agent wants to execute *another* tool based on the new results
    approvalRequests = response.Messages
        .SelectMany(m => m.Contents)
        .OfType<ToolApprovalRequestContent>()
        .ToList();
}

// 6. Final Synthesis
Console.WriteLine($"\nSenior Mentor:\n{response.Text}");